apiVersion: batch/v1
kind: CronJob
metadata:
  name: home-consumer
spec:
  schedule: "20,50 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: home-consumer
            image: aam411/k8shomeconsumer:3.0
            #image: aam411/testconsumer:
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
