# soup-backend-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: soup-backend
  labels:
    type: backend
  namespace: ser-mgt
spec:
  selector:
    type: backend
  ports:
  - protocol: 'TCP'
    port: 8000
    targetPort: 8000