# soup-backend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup-backend
  labels:
    type: backend
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      type: backend
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: soup-backend
          image: 664966433367.dkr.ecr.ap-northeast-2.amazonaws.com/soup-backend:345f49e49e73cf046fbbea5e342761cf535b735f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://soup-mysql:3306/soup?characterEncoding=UTF-8&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: pass123#
            - name: SPRING_REDIS_HOST
              value: soup-redis
            - name: SPRING_REDIS_PORT
              value: '6379'
            - name: ELASTICSEARCH_HOST
              value: '192.168.56.110'
            - name: ELASTICSEARCH_PORT
              value: '9200'
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
