apiVersion: batch/v1
kind: CronJob
metadata:
  name: street-crawler
spec:
  schedule: "*/30 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: street-crawler
            image: aam411/k8sstreetcrawler:2.0
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
