apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: client
    nodePort: 30007
  selector:
    app: redis-cluster