apiVersion: v1
kind: ConfigMap
metadata:
  name: soup-backend-config
  namespace: ser-mgt
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://dbcluster.mysql-operator.svc.cluster.local:3306/soup?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  SPRING_REDIS_HOST: soup-redis
  SPRING_REDIS_PORT: '6379'
  ELASTICSEARCH_HOST: a71fa846b45864e3aa708a894cbe9338-203128187.ap-northeast-2.elb.amazonaws.com
  ELASTICSEARCH_PORT: '80'
