# soup-admin-backend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup-admin-backend
  labels:
    type: admin-backend
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      type: admin-backend
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: admin-backend
    spec:
      containers:
        - name: soup-admin-backend
          image: 2214yj/soup-admin-service:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: soup-backend-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soup-backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
