# soup-search-backend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup-search-backend
  labels:
    type: search-backend
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      type: search-backend
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: search-backend
    spec:
      containers:
        - name: soup-search-backend
          image: 2214yj/soup-search-service:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: soup-backend-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soup-backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: ELASTICSEARCH_HOST
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: ELASTICSEARCH_PORT
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
