apiVersion: v1
kind: ConfigMap
metadata:
  name: soup-backend-config
  namespace: ser-mgt
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://dbcluster.mysql-operator.svc.cluster.local:3306/soup?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  SPRING_REDIS_HOST: soup-redis
  SPRING_REDIS_PORT: '6379'
  ELASTICSEARCH_HOST: aeedc3ed6750c447aaa648831cb233b1-592820155.ap-northeast-2.elb.amazonaws.com
  ELASTICSEARCH_PORT: '80'
