# soup-admin-backend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup-admin-backend
  labels:
    type: admin-backend
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: admin-backend
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: admin-backend
    spec:
      nodeSelector:
        eks/nodegroup-name: ng1-soup-cluster1
      containers:
        - name: soup-admin-backend
          image: 664966433367.dkr.ecr.ap-northeast-2.amazonaws.com/soup-admin-backend:9f89cc3b28a5998d3563cc351c358c23491fecf9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: soup-backend-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soup-backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
            - name: logging
              mountPath: /var/log/containers
            - name: logging2
              mountPath: /logs
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
        - name: logging
          hostPath:
            path: /var/lib/docker/containers
        - name: logging2
          hostPath:
            path: /var/lib/docker/containers
