# soup-search-backend-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: soup-search-backend
  labels:
    type: search-backend
  namespace: ser-mgt
spec:
  selector:
    type: search-backend
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000