# soup-member-backend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup-member-backend
  labels:
    type: member-backend
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      type: member-backend
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: member-backend
    spec:
      nodeSelector:
        eks/nodegroup-name: ng1-soup-cluster1
      containers:
        - name: soup-member-backend
          image: 664966433367.dkr.ecr.ap-northeast-2.amazonaws.com/soup-member-backend:d9a8b0bbe83eee9744b224664d2c5eeeb31ce53f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
               secretKeyRef:
                 name: soup-backend-secret
                 key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soup-backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: soup-backend-config
                  key: SPRING_REDIS_PORT
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
