apiVersion: batch/v1
kind: CronJob
metadata:
  name: home-crawler
spec:
  schedule: "*/30 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: home-crawler
            image: aam411/k8shomecrawler:4.0
            imagePullPolicy: IfNotPresent
            env:
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-host-port
                  key: KAFKA_PORT
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-host-port
                  key: KAFKA_HOST
          restartPolicy: Never
