apiVersion: batch/v1
kind: CronJob
metadata:
  name: kakao-crawler
spec:
  schedule: "*/30 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: kakao-crawler
            image: aam411/k8skakaocrawler:2.0
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
