apiVersion: batch/v1
kind: CronJob
metadata:
  name: street-consumer
spec:
  schedule: "20,50 * * * *" # 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: street-consumer
            image: aam411/k8sstreetconsumer:4.1
            imagePullPolicy: IfNotPresent
            env:
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_PORT
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_HOST
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: ELASTICSEARCH_HOST
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: ELASTICSEARCH_PORT
          restartPolicy: Never
