apiVersion: v1
kind: Service
metadata:
  labels:
    type: inmemory
  name: soup-redis
  namespace: ser-mgt
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    type: inmemory
  type: ClusterIP