# soup-mysql-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soup-mysql-pv
  labels:
    type: rdb
  namespace: ser-mgt
spec:
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b582f4111a1af698
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain