# soup-mysql-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: rdb
  name: soup-mysql
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      type: rdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        type: rdb
    spec:
      nodeSelector:
        eks/nodegroup-name: ng1-soup-cluster1
      containers:
      - image: mysql:5.7-debian
        name: soup-mysql
        args:
        - --character-set-client-handshake=false
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --explicit_defaults_for_timestamp=1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass123#
        - name: MYSQL_DATABASE
          value: soup
        - name: MYSQL_ROOT_HOST
          value: '%'
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
        - name: soup-mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      - name: soup-mysql-storage
        persistentVolumeClaim:
          claimName: soup-mysql-pvc