# soup-redis-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    type: inmemory
  name: soup-redis
  namespace: ser-mgt
spec:
  nodeSelector:
    eks/nodegroup-name: ng1-soup-cluster1
  containers:
  - image: redis:alpine3.16
    name: soup-redis
    ports:
    - containerPort: 6379
