# soup-frontend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup-frontend
  labels:
    type: frontend
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
      annotations:
        container.apparmor.security.beta.kubernetes.io/soup-frontend: unconfined
    spec:
      containers:
        - image: aramu/soup-frontend:2.3
          name: soup-frontend
          env:
            - name: MEMBER_URI
              value: soup-backend:8002
            - name: ADMIN_URI
              value: soup-backend:8001
            - name: SEARCH_URI
              value: soup-backend:8000
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
