# soup-frontend-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup-frontend
  labels:
    type: frontend
  namespace: ser-mgt
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
      annotations:
        container.apparmor.security.beta.kubernetes.io/soup-frontend: unconfined
    spec:
      nodeSelector:
        eks/nodegroup-name: ng1-soup-cluster1
      containers:
        - image: 664966433367.dkr.ecr.ap-northeast-2.amazonaws.com/soup-frontend:4168b345b1a6b91f319167318192a26146d9779f
          name: soup-frontend
          env:
            - name: MEMBER_URI
              value: soup-member-backend:8002
            - name: ADMIN_URI
              value: soup-admin-backend:8001
            - name: SEARCH_URI
              value: soup-search-backend:8000
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
